import { expect, test } from '@playwright/test';
import { createHmac } from 'node:crypto';

test('a seller signs in, publishes after review and receives confirmed featured placement', async ({ page }) => {
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(String(error)));
  const email = `marketplace-${Date.now()}@example.com`;
  await page.goto('/sell');
  await expect(page.getByRole('heading', {name:'Your property. A wider perspective.'})).toBeVisible();
  await page.getByRole('link', {name:'List your property for free'}).click();
  await page.getByLabel('Email address', {exact:true}).fill(email);
  await page.getByLabel('Password', {exact:true}).fill('a-long-e2e-property-password');
  await page.locator('[name="terms"]').check();
  await page.getByRole('button', {name:'Create account', exact:true}).click();
  await expect(page.locator('#recovery-key')).toHaveText(/^[A-Za-z0-9_-]{43}$/);
  await page.getByRole('link', {name:'I saved it — continue'}).click();
  await expect(page).toHaveURL(/\/sell\/new$/);
  await page.getByLabel('Property title', {exact:true}).fill('A courtyard home for the end-to-end check');
  await page.getByLabel('City or town', {exact:true}).fill('Mussomeli');
  await page.getByRole('combobox', {name:'Country', exact:true}).selectOption('Italy');
  await page.getByLabel('Asking price', {exact:true}).fill('45000');
  await page.getByLabel('Tell buyers about the property', {exact:true}).fill('A local-only test property with a courtyard and two rooms. This synthetic advertisement never reaches production.');
  await page.getByLabel('Seller / agency name', {exact:true}).fill('Local test owner');
  await page.locator('[name="authority"]').check();
  await page.locator('[name="photo_rights"]').check();
  const photo = await page.evaluate(() => { const canvas=document.createElement('canvas');canvas.width=80;canvas.height=80;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#ccb17b';ctx.fillRect(0,0,80,80);return canvas.toDataURL('image/png').split(',')[1]; });
  await page.locator('#photo-upload').setInputFiles({name:'local-test.png',mimeType:'image/png',buffer:Buffer.from(photo,'base64')});
  await expect(page.locator('#upload-previews img')).toHaveCount(1);
  await page.getByRole('button', {name:'Save draft & preview'}).click();
  await expect(page).toHaveURL(/\/seller\/properties\/seller-/);
  const listingId = page.url().split('/').pop()!;
  await expect(page.getByText('Your private preview · draft')).toBeVisible();
  await page.getByRole('button', {name:'Submit for review'}).click();
  await expect(page).toHaveURL(/\/account$/);
  await expect(page.locator('.status-pill')).toHaveText('pending');

  await page.goto('/admin/claim');
  await page.getByLabel('Private owner setup key').fill('e2e-owner-setup-not-a-secret');
  await page.getByRole('button', {name:'Claim owner access'}).click();
  await expect(page).toHaveURL(/\/admin$/);
  await page.getByLabel('Area latitude').fill('37.58');
  await page.getByLabel('Area longitude').fill('13.75');
  await page.locator('.admin-listing [name="reviewed"]').check();
  await page.getByRole('button', {name:'Apply review'}).click();
  await expect(page.locator('.admin-listing .status-pill')).toHaveText('published');
  await page.goto('/promote/'+listingId);
  await page.locator('[name="availability_confirmed"]').check();
  await page.locator('[name="terms"]').check();
  await page.route('https://buy.stripe.com/**', route => route.fulfill({contentType:'text/html',body:'<p>Local checkout stand-in. No Stripe request or charge.</p>'}));
  await page.getByRole('button', {name:'Continue to secure payment'}).click();
  await expect(page).toHaveURL(/buy\.stripe\.com\/local-only-fixture/);
  const orderId = new URL(page.url()).searchParams.get('client_reference_id')!;
  expect(orderId).toMatch(/^[a-f0-9]{48}$/);

  const sessionId = 'cs_test_marketplaceE2E123456';
  const event = {id:'evt_marketplaceE2E'+Date.now(),type:'checkout.session.completed',livemode:false,data:{object:{id:sessionId,client_reference_id:orderId,payment_status:'paid',mode:'payment',livemode:false,currency:'chf',amount_total:4900,payment_link:'plink_e2e_promotion',payment_intent:'pi_marketplaceE2E123456',metadata:{venture:'zorbeck',offering:'promotion'}}}};
  const payload=JSON.stringify(event), stamp=Math.floor(Date.now()/1000);
  const signature=createHmac('sha256','marketplace-e2e-signing-key').update(stamp+'.'+payload).digest('hex');
  const receipt = await page.request.post('/api/marketplace/stripe',{data:payload,headers:{'Stripe-Signature':`t=${stamp},v1=${signature}`,'Content-Type':'application/json'}});
  expect(receipt.status()).toBe(200);
  await page.goto('/payments/return?session_id='+sessionId);
  await expect(page.getByRole('heading',{name:'Payment confirmed.'})).toBeVisible();
  await page.goto('/search?location=Italy');
  await expect(page.locator('.property-card:visible').first()).toHaveAttribute('data-property',listingId);
  await expect(page.locator('.property-card:visible').first()).toContainText('Featured · paid placement');
  await page.goto('/properties/'+listingId);
  await expect(page.locator('.property-hero img')).toBeVisible();
  await page.getByRole('button',{name:'Save to account'}).click();
  await expect(page.getByRole('button',{name:'Saved to your account'})).toBeVisible();
  await page.goto('/account');
  await expect(page.locator('.shortlist-item')).toHaveCount(1);
  await expect(page.locator('body')).toContainText('CHF 49.00');

  // Remove the synthetic listing from discovery after the workflow assertion.
  await page.locator('.account-listing select[name="action"]').selectOption('withdraw');
  await page.locator('.account-listing').getByRole('button',{name:'Update',exact:true}).click();
  await expect(page.locator('.account-listing .status-pill')).toHaveText('withdrawn');
  await page.getByRole('button',{name:'Log out',exact:true}).click();
  await expect(page).toHaveURL(/\/$/);
  expect(errors).toEqual([]);
});
